jest.mock('../../config/database',()=>({query:jest.fn(),getClient:jest.fn()}));
import {getClient,query} from '../../config/database';
import {ProductMaintenanceRepository} from '../ProductMaintenanceRepository';
const queryMock=query as jest.Mock;
function client(rows:unknown[][]){const db={query:jest.fn(),release:jest.fn()};db.query.mockImplementation(async(sql:string)=>({rows:/^(BEGIN|COMMIT|ROLLBACK)/.test(sql)?[]:rows.shift()||[]}));(getClient as jest.Mock).mockResolvedValue(db);return db;}
beforeEach(()=>jest.clearAllMocks());
test('proposal uniqueness remembers rejected suggestions',async()=>{queryMock.mockResolvedValue({rows:[]});expect(await new ProductMaintenanceRepository().propose({} as any,{} as any,{} as any)).toBe(false);expect(queryMock.mock.calls[0][0]).toContain("product_maintenance_suggestions.status='pending'");});
test('repeat approval commits without product changes or duplicate audit',async()=>{const db=client([[{id:'1',status:'approved'}]]);expect(await new ProductMaintenanceRepository().review('1','approve','admin',undefined,jest.fn())).toEqual({id:'1',status:'approved'});expect(db.query.mock.calls.map(c=>c[0])).toEqual(['BEGIN',expect.stringContaining('FOR UPDATE'),'COMMIT']);});
test('undo refuses a product changed after approval and rolls back',async()=>{const db=client([[{id:'1',status:'approved',product_id:'3',canonical_product_id:'2',applied_product_updated_at:'2026-09-05 00:00:00.123456'}],[{canonical_product_id:'4'}],[]]);await expect(new ProductMaintenanceRepository().review('1','undo','admin',undefined,jest.fn())).rejects.toThrow('undo conflict');expect(db.query.mock.calls.some(c=>c[0]==='ROLLBACK')).toBe(true);expect(db.query.mock.calls.some(c=>c[0].includes('INSERT INTO product_maintenance_reviews'))).toBe(false);expect(db.release).toHaveBeenCalled();});
test('approval does not overwrite a classification assigned elsewhere',async()=>{const db=client([[{id:'1',status:'pending',product_id:'3',canonical_product_id:'2',mapping_id:'4'}],[{canonical_product_id:'8'}],[],[{product_id:'3'}],[{canonical_product_id:'2'}],[]]);await expect(new ProductMaintenanceRepository().review('1','approve','admin',undefined,jest.fn())).rejects.toThrow('classification conflict');expect(db.query.mock.calls.some(c=>c[0].startsWith('UPDATE products'))).toBe(false);});
